# Justfile — software quality assurance for the screen workspace.
# Run `just` to list recipes. See `_docs/QA.md` for what each does and when to run it.
#
# Tiered targets:
#   gate    — every code drop. Fast (~30s). Runs locally before marking a task done.
#   pr      — before pushing a PR. gate + supply-chain audit + coverage report.
#   release — before publishing. pr + semver + msrv + perf + advanced safety.
#   full    — literally everything (slow).

set shell := ["bash", "-uc"]

# Default: list recipes
default:
    @just --list --unsorted

# ─── Per-task gate (fast, runs before every task closure) ─────────────────────

# Format check (no edits). Use `fmt-fix` to auto-format.
fmt:
    cargo fmt --all --check

# Apply formatting in place.
fmt-fix:
    cargo fmt --all

# Compiler correctness — type-check the whole workspace.
check:
    cargo check --workspace --all-targets --all-features

# Clippy — pedantic lints, treat warnings as errors.
lint:
    cargo clippy --workspace --all-targets --all-features -- -D warnings

# Tests via nextest. Excludes `app-e2e` because Tier-2 e2e tests require
# `tauri-driver` + `webkit2gtk-driver` that aren't on the default `gate`
# host. Run e2e separately via `just e2e`.
test:
    cargo nextest run --workspace --exclude app-e2e --all-features

# Doc tests (nextest doesn't run them).
doctest:
    cargo test --workspace --doc

# Generate docs (warn-level missing_docs allowed — used in `gate`).
docs:
    cargo doc --workspace --no-deps --document-private-items

# Strict docs — broken intra-doc links and rustdoc warnings become errors.
# Use this before milestone close; gate uses the lenient `docs` so backfill
# doesn't block unrelated chunks.
docs-strict:
    RUSTDOCFLAGS="-D warnings -D rustdoc::broken_intra_doc_links -D rustdoc::private_intra_doc_links" cargo doc --workspace --no-deps --document-private-items

# Build the prose site (mdBook) and combine with rustdoc under target/book/.
# Output: target/book/index.html (prose) + target/book/api/<crate>/index.html (rustdoc).
#
# `--dest-dir` is resolved relative to the source dir, so we pass an absolute
# path rooted at the workspace.
# Build the in-repo mdBook preprocessor binary so `mdbook build` can find
# it on PATH via the recipes below. The first mdbook call after a clean
# would otherwise fail because the preprocessor isn't installed globally.
preprocessor-build:
    @cargo build -p mdbook-preprocessor-cross

site: docs preprocessor-build site-screen site-wisp
    @echo
    @echo "Open: file://$(pwd)/target/book/index.html  (screen project book)"
    @echo "      file://$(pwd)/target/book/wisp/index.html  (wisp library book)"

# Build the screen project book. Standalone recipe so CI can target a
# single book without rebuilding the other.
site-screen: preprocessor-build
    @mkdir -p target/book
    PATH="$(pwd)/target/debug:$PATH" mdbook build _docs/book --dest-dir "$(pwd)/target/book"
    @rm -rf target/book/api && cp -r target/doc target/book/api

# Build the wisp library book into `target/book/wisp/` so the two books
# compose into one site rooted at `target/book/`. Standalone target so
# the wisp-only CI gate can build it without touching the screen book.
site-wisp: preprocessor-build
    @mkdir -p target/book
    PATH="$(pwd)/target/debug:$PATH" mdbook build _docs/wisp-book --dest-dir "$(pwd)/target/book/wisp"

# Regenerate per-feature screenshots / story HTML into _docs/book/src/assets/.
# Used by mdBook chapters; commit the output so docs build is reproducible.
snapshots: snapshots-wisp snapshots-ui

snapshots-wisp:
    cargo run -p wisp-storybook --bin wisp-export-stories
    cargo run -p wisp-storybook --bin wisp-export-text-screenshots

# Render animated stories to MP4 via gstreamer. Local-only —
# gstreamer must be installed (`brew install gstreamer`). Not chained
# into `just snapshots-wisp` because it depends on a non-Rust runtime
# tool; run explicitly when an animated story's tick changes.
snapshots-wisp-animated:
    cargo run -p wisp-storybook --bin wisp-export-animated

snapshots-ui:
    cargo run -p ui-storybook --bin ui-export-stories

# Render the media mdBook visual assets — waveform + histogram PNGs
# for the M-MEDIA.4/.5/.7/.8 chapters. Local-only (depends on
# gstreamer + the bundled MP3 fixture). CI consumes the committed
# PNGs. The companion video asset (media/video-capture.mp4) is
# regenerated by `just snapshots-media-video` since it spawns
# gst-launch directly.
snapshots-media:
    cargo run -p media --example render-mdbook-assets

snapshots-media-video:
    gst-launch-1.0 -q -e videotestsrc num-buffers=90 is-live=false ! \
      "video/x-raw,format=I420,width=320,height=240,framerate=30/1" ! \
      x264enc tune=zerolatency speed-preset=fast bitrate=1000 ! \
      mp4mux ! filesink location=_docs/book/src/assets/media/video-capture.mp4

# Snapshot completeness gate.
# Every mdBook chapter (in either book + the shared fragments)
# that references an asset under any `assets/` MUST have that asset
# committed. Re-running the storybook exporters across machines is
# non-deterministic (Metal vs lavapipe etc.), so we don't
# byte-compare. We DO verify that every referenced file exists —
# catches "added a chapter, forgot to commit the PNG." Run
# `just snapshots` locally before committing if you changed a
# story's rendered output.
snapshots-check:
    #!/usr/bin/env bash
    set -euo pipefail
    missing=0
    # Find every `assets/...` reference in markdown chapters, resolve
    # relative to the chapter's directory, and check existence.
    while IFS= read -r chapter; do
      chapter_dir="$(dirname "$chapter")"
      # markdown image syntax: ![alt](path) or <iframe src="path">
      python3 - "$chapter" "$chapter_dir" <<'PY'
    import re, sys, os
    chapter, chapter_dir = sys.argv[1], sys.argv[2]
    text = open(chapter).read()
    refs = re.findall(r'!\[[^\]]*\]\(([^)]+)\)|src="([^"]+)"', text)
    flat = [a or b for a, b in refs]
    missing = []
    for ref in flat:
        if ref.startswith(('http://', 'https://')):
            continue
        # Only check assets/ references — code links / api links live elsewhere.
        if '/assets/' not in ref:
            continue
        path = os.path.normpath(os.path.join(chapter_dir, ref))
        if not os.path.exists(path):
            missing.append((chapter, ref, path))
    for c, r, p in missing:
        print(f"MISSING ASSET: {c} → {r} (resolved {p})", file=sys.stderr)
    sys.exit(1 if missing else 0)
    PY
    done < <(find _docs/book/src _docs/wisp-book/src _docs/shared -name "*.md" -type f 2>/dev/null)
    echo "snapshots-check: all referenced assets present (screen + wisp + shared)."

# Diagrams must be mermaid, not ASCII.
# Rejects any chapter under `_docs/book/src/`, `_docs/wisp-book/src/`,
# or `_docs/shared/` containing box-drawing characters
# (┌ │ └ ├ ═ ╔ ╗) or the unicode arrow runs `─►` / `──▶` / `◄──`
# outside of allowlisted files. The allowlist covers:
#   - orientation/stack.md — directory-tree listing (mermaid is poor at file trees)
# Math formulas, type-signature legends, and shell pipelines that
# happen to contain `!` etc. are fine because they don't use these
# specific glyphs.
mermaid-check:
    #!/usr/bin/env bash
    set -euo pipefail
    allowlist=(
      "_docs/book/src/orientation/stack.md"
    )
    is_allowed() {
      local f="$1"
      for a in "${allowlist[@]}"; do
        [[ "$f" == "$a" ]] && return 0
      done
      return 1
    }
    violations=0
    while IFS= read -r file; do
      if is_allowed "$file"; then
        continue
      fi
      if grep -nP '[┌│└├═╔╗]|─►|──▶|◄──' "$file" >/dev/null 2>&1; then
        echo "ASCII DIAGRAM IN MDBOOK CHAPTER: $file" >&2
        grep -nP '[┌│└├═╔╗]|─►|──▶|◄──' "$file" >&2 || true
        violations=$((violations + 1))
      fi
    done < <(find _docs/book/src _docs/wisp-book/src _docs/shared -name '*.md' -type f 2>/dev/null)
    if [ $violations -gt 0 ]; then
      echo "" >&2
      echo "Found $violations file(s) with ASCII diagrams." >&2
      echo "Per CLAUDE.md 'Diagrams in mdBook — mermaid only, no ASCII'," >&2
      echo "convert to a \`\`\`mermaid block." >&2
      echo "Prefer sequenceDiagram when participants exchange messages over time." >&2
      exit 1
    fi
    echo "mermaid-check: no ASCII diagrams in mdBook chapters."

# Drift gate for the two-book setup. Walks both books for
# `{{shared path}}` and `{{wisp-link path}}` tags and asserts:
#   1. every `{{shared X}}` resolves to an existing file under
#      `_docs/shared/`,
#   2. the rendered HTML doesn't carry any
#      `mdbook-preprocessor-cross: ... error` comments (a missing
#      fragment in production emits one of those).
# Run as part of `gate` so a typo in a shared/wisp-link tag fails
# CI before deploy.
shared-check: site
    #!/usr/bin/env bash
    set -euo pipefail
    python3 - <<'PY'
    import os, re, sys
    SHARED = re.compile(r'\{\{\s*shared\s+([^}]+?)\s*\}\}')
    fail = 0
    for root in ("_docs/book/src", "_docs/wisp-book/src"):
        for dirpath, _, files in os.walk(root):
            for f in files:
                if not f.endswith(".md"):
                    continue
                p = os.path.join(dirpath, f)
                text = open(p).read()
                for m in SHARED.finditer(text):
                    ref = m.group(1).strip()
                    if not os.path.isfile(os.path.join("_docs/shared", ref)):
                        print(f"MISSING SHARED FRAGMENT: {p} → _docs/shared/{ref}", file=sys.stderr)
                        fail = 1
    sys.exit(fail)
    PY
    # Belt-and-braces: rendered HTML must not carry the preprocessor's
    # error sentinel (catches runtime-only failures the source grep
    # cannot see — unreadable files, typo'd tag forms, etc.).
    # Exclude `target/book/api/` because rustdoc renders the preprocessor's
    # own source — the error-comment template would otherwise match itself.
    if grep -rE 'mdbook-preprocessor-cross[^>]*error' target/book --exclude-dir=api 2>/dev/null; then
      echo "RUNTIME ERROR COMMENT IN RENDERED HTML — see above." >&2
      exit 1
    fi
    echo "shared-check: all shared() references resolve and no runtime errors in rendered HTML."

# Per-task gate. Run before marking any task done.
gate: fmt check lint test doctest docs snapshots-check mermaid-check shared-check

# ─── Remote-first UI dev loop (DEV-00..DEV-08 / AUT-145..AUT-153) ─────────────

# Local-only storybook dev loop. Watches ui-storybook src + assets,
# re-runs export-stories on change, browser auto-reloads via WebSocket.
# Visit http://127.0.0.1:3000/ to see the storybook index.
#
# For phone access over Tailscale, see `just dev-remote`.
dev:
    cargo run -p dev-server --release -- \
        --assets _docs/book/src/assets/ui \
        --watch crates/ui-storybook/src crates/ui-storybook/assets \
        --port 3000 \
        --host 127.0.0.1

# Remote-accessible storybook for phone preview. Starts `dev` in the
# background, exposes the local server via Tailscale Serve, prints the
# phone-reachable HTTPS URL. Requires Tailscale installed + signed in
# (see _docs/book/src/conventions/remote-dev.md for one-time setup).
#
# Stop with: `just dev-remote-stop`.
dev-remote:
    @echo "Booting dev-server in background (logs: /tmp/screen-dev-server.log)…"
    @nohup just dev > /tmp/screen-dev-server.log 2>&1 &
    @sleep 4
    @echo "Exposing via Tailscale Serve…"
    tailscale serve --bg http://127.0.0.1:3000
    @echo ""
    @echo "Phone URL:"
    @tailscale serve status | grep -Eo 'https://[^ ]+' | head -1 || echo "(check 'tailscale serve status' manually)"
    @echo ""
    @echo "Stop with:  just dev-remote-stop"

# Tear down the background dev-server + Tailscale Serve config opened by
# `just dev-remote`.
dev-remote-stop:
    @echo "Stopping Tailscale Serve…"
    -tailscale serve --https=443 off
    @echo "Killing background dev-server…"
    -pkill -f "target/release/dev-server" || true
    @echo "Done."

# Tier-2 e2e tests. Requires `tauri-driver` and (on Linux) `webkit2gtk-driver`
# + `xvfb`. Linux runs the suite under `xvfb-run` for headless display;
# macOS prints a clear skip message because `tauri-driver`'s WKWebView
# support is incomplete upstream (see _docs/book/src/app-ui/testing.md).
e2e:
    #!/usr/bin/env bash
    set -euo pipefail
    case "$(uname -s)" in
      Linux*)
        if ! command -v tauri-driver >/dev/null 2>&1; then
          echo "ERROR: tauri-driver not on PATH"
          echo "  install: cargo install --locked tauri-driver"
          exit 1
        fi
        if ! command -v xvfb-run >/dev/null 2>&1; then
          echo "ERROR: xvfb-run not on PATH"
          echo "  install: sudo apt-get install -y xvfb"
          exit 1
        fi
        echo "→ running Tier-2 e2e under xvfb-run …"
        xvfb-run --auto-servernum cargo nextest run -p app-e2e
        ;;
      Darwin*)
        echo "⚠ macOS Tier-2 e2e skipped — tauri-driver doesn't reliably"
        echo "  drive WKWebView. Use Linux CI for the gate; mac uses"
        echo "  manual smoke before tagging. Tier-1 (\`just gate\`) still"
        echo "  runs the IPC harness cross-platform."
        ;;
      *)
        echo "⚠ Tier-2 e2e: unrecognized platform $(uname -s); skipping."
        ;;
    esac

# Run the wisp-storybook GUI — one window with every shipped feature.
storybook:
    cargo run -p wisp-storybook --release

# Run the UI storybook (Leptos) in the browser via Trunk.
ui-storybook:
    cd crates/ui-storybook && trunk serve --no-default-features --features csr --open

# Build the recorder shell (Leptos CSR) — dev server with hot reload.
app-ui:
    cd crates/app-ui && trunk serve --open

# Production-build the recorder shell into `crates/app-ui/dist/`.
app-ui-build:
    cd crates/app-ui && trunk build --release

# ─── Supply chain & dependency hygiene ────────────────────────────────────────

# RustSec advisory check.
audit:
    cargo audit

# License + advisory + bans + sources policy.
deny:
    cargo deny check

# Find unused dependencies.
unused-deps:
    cargo machete

# Optional/nightly: stricter unused-deps detection.
unused-deps-strict:
    cargo +nightly udeps --workspace --all-targets

# All supply chain & dep checks.
# `cargo deny check` covers RustSec advisories; cargo-audit is available
# standalone via `just audit` but redundant in the chain.
security: deny unused-deps

# ─── Coverage ──────────────────────────────────────────────────────────────────

# LCOV report (for IDE integration).
coverage:
    cargo llvm-cov nextest --workspace --all-features --lcov --output-path lcov.info

# HTML report (for humans).
coverage-html:
    cargo llvm-cov nextest --workspace --all-features --html
    @echo "Open target/llvm-cov/html/index.html"

# ─── API stability ─────────────────────────────────────────────────────────────

# Detect breaking API changes (run before releasing).
semver:
    cargo semver-checks check-release

# Snapshot the public API surface.
public-api:
    cargo public-api --workspace

# Find minimum supported Rust version.
msrv:
    cargo msrv find

# ─── Performance ──────────────────────────────────────────────────────────────

# Run benchmarks.
bench:
    cargo bench --workspace

# Binary size analysis (largest crates).
bloat:
    cargo bloat --release --crates

# Generate a flamegraph for an example.
flamegraph EXAMPLE:
    cargo flamegraph --example {{EXAMPLE}}

# ─── Safety ───────────────────────────────────────────────────────────────────

# Count unsafe blocks across the dep tree.
geiger:
    cargo geiger

# Pure-Rust modules under miri (interpreter-based UB detection).
# wgpu/winit code can't run under miri — only modules that don't touch GPU/IO.
miri:
    cargo +nightly miri test -p wisp --lib -- color blend math

# Mutation testing — flips operators/conditions, asserts tests still fail.
mutants:
    cargo mutants --workspace

# ─── Tier aggregates ─────────────────────────────────────────────────────────

# Per-PR check — run before pushing.
pr: gate security coverage

# Per-release check — run before publishing.
release: pr semver msrv bench bloat geiger

# Everything (slow — includes mutants, miri).
full: release miri mutants

# ─── Bootstrap ────────────────────────────────────────────────────────────────

# Install QA tools needed for the per-task gate (run once per machine).
bootstrap:
    @echo "Installing per-task gate tools…"
    cargo install --locked cargo-nextest
    cargo install --locked cargo-deny
    cargo install --locked cargo-audit
    cargo install --locked cargo-machete
    cargo install --locked mdbook
    @echo
    @echo "Optional tools (install on demand):"
    @echo "  cargo install --locked cargo-llvm-cov   # coverage"
    @echo "  cargo install --locked cargo-semver-checks"
    @echo "  cargo install --locked cargo-public-api"
    @echo "  cargo install --locked cargo-msrv"
    @echo "  cargo install --locked cargo-bloat"
    @echo "  cargo install --locked cargo-geiger"
    @echo "  cargo install --locked cargo-mutants"
    @echo "  cargo install --locked cargo-flamegraph # also needs perf/dtrace"
    @echo "  rustup component add miri --toolchain nightly"
    @echo "  rustup component add llvm-tools-preview"
